name: "Copilot Setup Steps"

on: workflow_dispatch
jobs:
  # Este é o nome do job obrigatório. Se for diferente, o Copilot irá ignorá-lo.
  copilot-setup-steps:
    runs-on: ubuntu-latest

    # Conceder ao Copilot acesso antecipado para ler o conteúdo do repository.
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt